### ISSUE TITLE
only get black screen on start

### ISSUE THREAD

**Issue by will-byrne** [redyf/nixdots#1]
Hi, love the look of the dots, I have tried to use them and my version are visible in a fork here: https://github.com/will-byrne/nixdots
Unfortunately when i do a rebuild with these files i get a tty login prompt and after I log in I only see a a black screen with a blinking underscore. 

I am fairly new to nixos and hyperland but not linux itself. I cant seem to figure out why it is not working so any pointers would be great.

**Comment by redyf** [comment]
Hello there, first of all thanks for the feedback! NixOS is quite hard to understand at first because it works in a different way if you compare to other popular distros. This config was made not only to share the dots but also help people understand how to create their own nix module structure. Keep in mind that everything might not work out of the box as warned in the README: "IMPORTANT: Do not use my configuration.nix and/or hardware-configuration.nix! These files include specific settings to my drives and are unlikely to have a positive reaction on your device!

It might not work perfectly right after installation, you have been warned!
For best security, make sure the files will not conflict with your current ones."

I've replicated my desktop setup on a 11 year old thinkpad and everything worked well, even hyprland, all I had to do was generate a new hardware.nix file for it. So maybe some setting in your device is in conflict with nixdots.

**Comment by will-byrne** [comment]
I used the hardware-configuration.nix from my existing gnome install which worked fine and I went through the configuration.nix line by line to make sure it would work on my machine. I honestly dont think either of those two files are the problem. Its almost like hyperland has no display manager to connect to as I couldnt find any wayland services running. Tomorrow ill try again and just regenerate the hardware.nix file.

**Comment by redyf** [comment]
Can you tell me your what's your cpu and gpu? Also I hope it works tomorrow 🙂

**Comment by will-byrne** [comment]
Sure I have an amd 5900x and an nvidia 1080ti.

**Comment by redyf** [comment]
Keep in mind that I'm using a intel cpu (i5-10400f) and a different nvidia gpu (1650 super). The drivers might be different for you. Also I suggest asking in hyprland's server for help as the issue seems to be with hyprland specifically.

**Comment by will-byrne** [comment]
turns out sleep is for the weak managed to get it working with:

```
boot.kernelParams = [ "i8042.dumbkbd=1" ];
systemd.services."display-manager".after = [ "network-online.target" "systemd-resolved.service" ];
```
and commenting out
```
hardware.nvidia.open = true;
```

Im still not sure how you are getting the scripts and autostart files from the flake hyprland folder into `~/.config/hypr`

**Comment by redyf** [comment]
I just copied them manually into .config folder xD

**Comment by will-byrne** [comment]
Ah no worries then I’ll see if I can automate that my side then. Thanks for all the help 😺

**Comment by redyf** [comment]
That would be great, let me know if you do it 😁

**Comment by will-byrne** [comment]
went a bit crazy changing my dots over the few days so making a pr would be a pain but the key bit for auto moving the scripts can be seen in this commit: https://github.com/will-byrne/nixdots/commit/ccbfe2caa3f796808c9cffc4cc4513ea402e74ad
